name: Test kedro-viz-gh-deploy-test Action

permissions:
  contents: write

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch the repository
        uses: actions/checkout@v4
      - name: Deploy Kedro-Viz to GH Pages
        uses: ./
        with:
          deploy_branch: "test-deploy"
          commit_message: "my test deployment"
          telemetry_consent: false
