name: Test kedro-viz-gh-deploy-test Action

permissions:
  contents: write

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch the repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install Project Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Deploy Kedro-Viz to GH Pages
        uses: ravi-kumar-pilla/shareableviz-action@main
        with:
          telemetry_consent: false
